### ISSUE TITLE
Won/lost column in leaderboard?

### ISSUE THREAD

**Issue by amonod** [eloitanguy/tarotbot#1]
Hi,
First of all thank you for this interesting and fun project.
I have a suggestion: would it be interesting to add an extra column in the leaderboard that features a `won/lost` stat (eg 32/14) ?
You would have to count the number of times each players wins either as a "preneur", "partenaire" or "défenseur ", or loses. 
I guess you could have a `preneur win/partenaire win/défenseur win/defenseur loose/partenaire loose/preneur loose` column instead but it would be a bit cluttered.

**Comment by eloitanguy** [comment]
Hi Antoine,

You can now see the W/L information by typing t/leaderboard2, which also sorts the players by [total points] / [games played]. See [the commit](https://github.com/eloitanguy/tarotbot/commit/2a839789896812efec0a0ec91eeef6e99dd799b4#diff-f55b7ff7a49f354237d4cd7f697d7ad966e47bbe9508707065d3a899fb2aae9b) and [the function `leaderboard2`](https://github.com/eloitanguy/tarotbot/blob/main/tarot_commands/leaderboard.py#L30).

I separated the leaderboard into the usual (sorted by total points) and this new one, otherwise it wouldn't be legible on mobile Discord.
